name: xzl-helper

on:
  #设置push运行
  push:
    #branches: [ main ]
  schedule:
    - cron: "55 13 * * *" # 该时间为UTC时间，比北京时间晚8个小时，每天晚上10点自动执行

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Run Project
        run: npm install && npm run server
