name: xzl-helper

on:
  #设置push运行
  #push:
    #branches: [ main ]
  schedule:
    - cron: "40 12 * * *" # 该时间为UTC时间，比北京时间晚8个小时，每天晚上8;40点自动执行
    #- cron: "55 13 * * *" # 该时间为UTC时间，比北京时间晚8个小时，每天晚上10点自动执行
jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Run Project
        run: npm install && npm run server
